{% set name = "pymmcore-widgets" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b23f71e0fe98f0dab9b3638c59076912f1dc804c486ef0bb751390d295f06929

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - fonticon-materialdesignicons6
    - pymmcore-plus >=0.6.3
    - python >=3.8
    - qtpy
    - superqt >=0.3.1
    - useq-schema >=0.1.2

test:
  imports:
    - pymmcore_widgets
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/pymmcore-plus/pymmcore-widgets
  summary: A set of Qt-based widgets onto the pymmcore-plus model
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
