{% set name = "pymmcore-widgets" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3c2f951922681aa1c4c4c9225928cb4a0475ba2e7ce5c1c73aa0fd253b0fd9c7


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - fonticon-materialdesignicons6
    - pymmcore
    - pymmcore-plus >=0.8.1
    - python >=3.8
    - qtpy >=2.0
    - superqt >=0.5.3
    - pint
    - useq-schema >=0.4.6

test:
  imports:
    - pymmcore_widgets
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/pymmcore-widgets
  summary: A set of Qt-based widgets onto the pymmcore-plus model
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/pymmcore-plus/pymmcore-widgets

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
