{% set name = "pymmcore-widgets" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymmcore-widgets-{{ version }}.tar.gz
  sha256: c7886a0953d630f871771f5671caf605aa2ec4c5d328e25ba6e631b9eb559e24

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - fonticon-materialdesignicons6
    - pymmcore-plus >=0.6.3
    - python >=3.8
    - qtpy
    - superqt >=0.3.1
    - useq-schema >=0.1.2

test:
  imports:
    - pymmcore_widgets
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/pymmcore-plus/pymmcore-widgets
  summary: A set of Qt-based widgets onto the pymmcore-plus model
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
